### ISSUE TITLE
Network issue: Selected class (model prefab) is not synced across clients

### ISSUE THREAD

**Issue by adamajammary** [adamajammary/imt3601#6]
Started multiplayer, one client had a rabbit and the other a fox, but one of the clients showed two foxes instead.

**Comment by Hifoz** [comment]
This is because the class is currently selected when the PlayerCharacters is initialized (SetupLocalPlayer.setupClass()).

This is was left like this from pull request #2, because I was thinking that the selection of class would be done by a character select screen eventually, so any means of syncing the random selection would only be temporary anyways.

Solution would be to create a character selector which selects the class (randomly or by player choice) for each player and calls their SetupLocalPlayer.setupClass() with the desired class instead of it being called on initialization of the PlayerCharacter.

**Comment by adamajammary** [comment]
should be fixed in new pull request, this issue can be closed after confirming that it works.
